name: Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            path/to/your/content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}