name: test

on:
  push:
    tags:
    - 'v*'
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  orchestrate:
    runs-on: ubuntu-latest

    steps:
        - name: Will succeed
          run: |
            echo "test"
            exit 0