name: workflow_runner

on:
  push:
    tags:
    - 'v*'
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  orchestrate:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Build Workflow
        uses: julianiag/workflow-trigger@v0.1.10
        with:
          # GitHub App ID
          appId: ${{ secrets.APP_ID }}
          # Private key associated with the GitHub App
          privateKey: ${{ secrets.APP_PRIVATE_KEY }}
          # GitHub App installation ID
          installationId: ${{ secrets.APP_INSTALLATION_ID }}
          # Owner of the repo (org name or account name)
          owner: your_owner_name
          # Name of the repository containing the workflow
          repo: your_repository_name
          # ID or name of the workflow to trigger
          workflowId: build.yml

      - name: Trigger Test Workflow
        uses: julianiag/workflow-trigger@v0.1.10
        with:
          # GitHub App ID
          appId: ${{ secrets.APP_ID }}
          # Private key associated with the GitHub App
          privateKey: ${{ secrets.APP_PRIVATE_KEY }}
          # GitHub App installation ID
          installationId: ${{ secrets.APP_INSTALLATION_ID }}
          # Owner of the repo (org name or account name)
          owner: your_owner_name
          # Name of the repository containing the workflow
          repo: your_repository_name
          # ID or name of the workflow to trigger
          workflowId: test.yml

      - name: Trigger Release Workflow
        uses: julianiag/workflow-trigger@v0.1.10
        with:
          # GitHub App ID
          appId: ${{ secrets.APP_ID }}
          # Private key associated with the GitHub App
          privateKey: ${{ secrets.APP_PRIVATE_KEY }}
          # GitHub App installation ID
          installationId: ${{ secrets.APP_INSTALLATION_ID }}
          # Owner of the repo (org name or account name)
          owner: your_owner_name
          # Name of the repository containing the workflow
          repo: your_repository_name
          # ID or name of the workflow to trigger
          workflowId: release.yml
